// Tearsheet data schema — generated by scripts/gen_tearsheet.py
// Used by PerformanceTearsheet server component
// To add a new slug: run gen_tearsheet.py with --slug <slug>
// and output will be written to content/studies/<slug>/tearsheet.json

export interface TearsheetData {
  // Metrics strip (7 KPIs)
  profitFactor: number;
  winRate: number;
  sample: number;
  wins: number;
  losses: number;
  netPts: number;
  avgR: number;
  maxDrawdown: number;
  recoveryFactor: number;

  // Quality factors table (8 rows)
  sharpe: number;
  calmar: number;
  sortino: number;
  avgWin: number;
  avgLoss: number;
  bestTrade: number;
  worstTrade: number;
  bestTradeDate: string;
  worstTradeDate: string;
  timeInMarketMinutes: number;

  // Equity curve points
  curve: Array<{
    date: string;
    cumulative: number;
    tradePnl: number;
    isWin: boolean;
  }>;

  // PnL distribution histogram
  distribution: Array<{
    binStart: number;
    binEnd: number;
    count: number;
  }>;

  // Trade sequence streaks
  streaks: Array<{ type: 'W' | 'L'; length: number }>;
  longestWStreak: number;
  longestLStreak: number;

  // Period meta
  periodStart: string;   // e.g. "2016"
  periodEnd: string;     // e.g. "2026"
  peakPts: number;
  peakDate: string;      // e.g. "Oct 2025"
  troughPts: number;     // negative value
  troughDate: string;    // e.g. "Nov 2022"

  // Display labels
  eventLabel: string;    // e.g. "FOMC"
  patternLabel: string;  // e.g. "IFVG + SMT"
  assetLabel: string;    // e.g. "NQ"
  subtitle: string;      // e.g. "10y backtest · NQ futures · SMT confirmation on ES"
}
